# app.py
# Streamlit frontend — native components only, no custom CSS.

import requests
import streamlit as st

BACKEND = "http://localhost:8000/getrecipe"

st.title("🍽️ AI Recipe Suggester")
st.caption("Enter your ingredients, calorie goal, and time — get a personalised recipe instantly.")

# ---------- Inputs ----------
ingredients = st.text_area("🥕 Ingredients (comma-separated)", placeholder="e.g. eggs, spinach, garlic, olive oil")
calories    = st.number_input("🔥 Target Calories (kcal)", min_value=50, max_value=5000, value=500, step=50)
time_limit  = st.slider("⏱️ Time Limit (minutes)", min_value=5, max_value=120, value=30, step=5)

# ---------- Submit ----------
if st.button("✨ Generate Recipe"):
    if not ingredients.strip():
        st.error("Please enter at least one ingredient.")
    else:
        with st.spinner("Thinking..."):
            try:
                res = requests.post(
                    BACKEND,
                    json={"ingredients": ingredients, "calories": int(calories), "time_limit": int(time_limit)},
                    timeout=60,
                )
            except requests.exceptions.ConnectionError:
                st.error("❌ Cannot reach the backend. Run: `uvicorn main:app --reload`")
                st.stop()
            except requests.exceptions.Timeout:
                st.error("❌ Request timed out. Please try again.")
                st.stop()

        if res.status_code != 200:
            st.error(f"❌ Error {res.status_code}: {res.json().get('detail', res.text)}")
            st.stop()

        r = res.json()

        # Cache status
        if r["cached"]:
            st.success("⚡ Result served from cache.")
        else:
            st.info("🌟 Fresh recipe generated by Gemini AI.")

        # Recipe display
        st.subheader(f"🍳 {r['title']}")

        col1, col2 = st.columns(2)
        col1.metric("Calories", f"{r['calories']} kcal")
        col2.metric("Time", f"{r['time_limit']} min")

        st.divider()

        st.markdown("**📋 Ingredients**")
        for item in r["ingredients_list"]:
            st.write(f"• {item}")

        st.divider()

        st.markdown("**👨‍🍳 Instructions**")
        for i, step in enumerate(r["instructions"], 1):
            st.write(f"**{i}.** {step}")
